### PR TITLE
Add in more simple birds, Proposal

### PR DESCRIPTION
**Pull request by MagnetarRocket**
I think of them not being phoenixes, but rather birds of paradise (an real but rare bird). Anyways these fit into an square better than the current bird. Also added in more "tropical" backgrounds for the base install, includes 4k and 8k versions.

### CODE REVIEW

**Comment by Toasterson** [comment]
Thanks for the contribution! Can you integrate them into the community page? If not I'll gladly add them there.

**Comment by MagnetarRocket** [comment]
How to contribute them into the community page?

________________________________________

**Comment by Toasterson** [comment]
Checkout my changes I pushed to this PR

https://github.com/OpenIndiana/website/pull/8/files#diff-975b1fba3185405d75c4d41f14f9c8190456050e49724257ddd1e51dba71f7e4

**Comment by Toasterson** [comment]
@MagnetarRocket any wishes for changes? Otherwise I'll merge this.

**Pull request merged**
